mappings:
  DeleteOrdersTask: ChristopherBolt\BoltShopTools\Tasks\DeleteOrdersTask
  CheckoutStep_CombinedShippingPayment: ChristopherBolt\BoltShopTools\Checkout\Step\CombinedShippingPayment
  CheckoutStep_BoltSummary: ChristopherBolt\BoltShopTools\Checkout\Step\BoltSummary
  CheckoutStep_CombinedDetails: ChristopherBolt\BoltShopTools\Checkout\Step\CombinedDetails
  CombinedShippingPaymentCheckoutComponent: ChristopherBolt\BoltShopTools\Checkout\Component\CombinedShippingPayment
  CombinedDetailsCheckoutComponent: ChristopherBolt\BoltShopTools\Checkout\Component\CombinedDetails
  BoltShopConfig: ChristopherBolt\BoltShopTools\Extensions\BoltShopConfig
  BoltShopLeftAndMain: ChristopherBolt\BoltShopTools\Extensions\BoltShopLeftAndMain
  BoltShippingMethod: ChristopherBolt\BoltShopTools\Extensions\BoltShippingMethod
  BoltPayment: ChristopherBolt\BoltShopTools\Extensions\BoltPayment
  BoltSpecificPricingExtension: ChristopherBolt\BoltShopTools\Extensions\BoltSpecificPricingExtension
  BoltShopMember: ChristopherBolt\BoltShopTools\Extensions\BoltShopMember
  BoltCheckoutPage: ChristopherBolt\BoltShopTools\Extensions\BoltCheckoutPage
  BoltAddress: ChristopherBolt\BoltShopTools\Extensions\BoltAddress
  BoltProductAttributeType: ChristopherBolt\BoltShopTools\Extensions\BoltProductAttributeType
  BoltProductVariation: ChristopherBolt\BoltShopTools\Extensions\BoltProductVariation
  BoltProductImage: ChristopherBolt\BoltShopTools\Extensions\BoltProductImage
  BoltProduct: ChristopherBolt\BoltShopTools\Extensions\BoltProduct
  BoltProduct_OrderItem: ChristopherBolt\BoltShopTools\Extensions\BoltProductOrderItem
  BoltProductAttributeValue: ChristopherBolt\BoltShopTools\Extensions\BoltProductAttributeValue
  BoltSpecificPrice: ChristopherBolt\BoltShopTools\Extensions\BoltSpecificPrice
  BoltAccountPage: ChristopherBolt\BoltShopTools\Extensions\BoltAccountPage
  BoltOrderManipulation: ChristopherBolt\BoltShopTools\Extensions\BoltOrderManipulation
  BoltCartPage: ChristopherBolt\BoltShopTools\Extensions\BoltCartPage
  BoltShopPage: ChristopherBolt\BoltShopTools\Extensions\BoltShopPage
  BoltProductCategory: ChristopherBolt\BoltShopTools\Extensions\BoltProductCategory
  BoltProductCategory_Controller: ChristopherBolt\BoltShopTools\Extensions\BoltProductCategoryController
  BoltGST: ChristopherBolt\BoltShopTools\Model\BoltGST
  BoltOrder: ChristopherBolt\BoltShopTools\Extensions\BoltOrder
  JsonPriceUpdater: ChristopherBolt\BoltShopTools\Controllers\JsonPriceUpdater
