---
Name: boltshoptoolsrequestprocessors
After:
  - requestprocessors
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        BoltShopConfigMiddleware: '%$ChristopherBolt\BoltShopTools\Middleware\BoltShopConfigMiddleware'
        BoltShopWindcaveMiddleware: '%$ChristopherBolt\BoltShopTools\Middleware\WindcaveMiddleware'
